import { type Module, inject } from 'langium';
import { createDefaultModule, createDefaultSharedModule, type DefaultSharedModuleContext, type LangiumServices, type LangiumSharedServices, type PartialLangiumServices } from 'langium/lsp';
import { SingleFileHistoryGeneratedModule, SingleFileHistoryGeneratedSharedModule } from './generated/module.js';
import { SingleFileHistoryValidator, registerValidationChecks } from './single-file-history-validator.js';
import { SingleFileHistoryCompletionProvider } from './single-file-history-completion.js';
//import { SingleFileHistoryCompletionProvider } from './single-file-history-completion.js';

/**
 * Declaration of custom services - add your own service classes here.
 */
export type SingleFileHistoryAddedServices = {
    validation: {
        SingleFileHistoryValidator: SingleFileHistoryValidator
    }
}

/**
 * Union of Langium default services and your custom services - use this as constructor parameter
 * of custom service classes.
 */
export type SingleFileHistoryServices = LangiumServices & SingleFileHistoryAddedServices

/**
 * Dependency injection module that overrides Langium default services and contributes the
 * declared custom services. The Langium defaults can be partially specified to override only
 * selected services, while the custom services must be fully specified.
 */
export const SingleFileHistoryModule: Module<SingleFileHistoryServices, PartialLangiumServices & SingleFileHistoryAddedServices> = {
    validation: {
        SingleFileHistoryValidator: () => new SingleFileHistoryValidator()
    },
    lsp: {
        CompletionProvider: (services) => new SingleFileHistoryCompletionProvider(services)
    }
};

/**
 * Create the full set of services required by Langium.
 *
 * First inject the shared services by merging two modules:
 *  - Langium default shared services
 *  - Services generated by langium-cli
 *
 * Then inject the language-specific services by merging three modules:
 *  - Langium default language-specific services
 *  - Services generated by langium-cli
 *  - Services specified in this file
 *
 * @param context Optional module context with the LSP connection
 * @returns An object wrapping the shared services and the language-specific services
 */
export function createSingleFileHistoryServices(context: DefaultSharedModuleContext): {
    shared: LangiumSharedServices,
    SingleFileHistory: SingleFileHistoryServices
} {
    const shared = inject(
        createDefaultSharedModule(context),
        SingleFileHistoryGeneratedSharedModule
    );
    const SingleFileHistory = inject(
        createDefaultModule({ shared }),
        SingleFileHistoryGeneratedModule,
        SingleFileHistoryModule
    );
    shared.ServiceRegistry.register(SingleFileHistory);
    registerValidationChecks(SingleFileHistory);
    if (!context.connection) {
        // We don't run inside a language server
        // Therefore, initialize the configuration provider instantly
        shared.workspace.ConfigurationProvider.initialized({});
    }
    return { shared, SingleFileHistory };
}
